Diff files

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,6 +2,8 @@ version: 2.1
 
 orbs:
   docker: circleci/docker@0.5.1
+  helm: circleci/helm@0.1.3
+  multirepo: dnephin/multirepo@0.0.7
 
 workflows:
   version: 2
@@ -13,17 +15,80 @@ workflows:
               only:
                 - master
 
+# commands:
+#   deploy:
+#     parameters:
+#       paths:
+#         type: string
+#         description: |
+#           A list of file paths used with 'git diff' to check for modification.
+#       upstream_branch:
+#         type: string
+#         description: |
+#           The upstream branch used with 'git merge-base' to find the most recent
+#           commit shared by HEAD and the upstream branch.
+#         default: origin/master
+#       working_directory:
+#         type: string
+#         description: |
+#           Directory to change to before executing the command.
+#         default: "$PWD"
+#       run_on_upstream:
+#         type: boolean
+#         description: |
+#           When run_on_upstream is true, and HEAD matches the upstream_branch the
+#           job always run. When false the job will not run when HEAD matches
+#           the upstream_branch.
+#         default: true
+
+
 jobs:
   deploy:
     docker:
-      - image: alpine/helm:2.13.0
+      - image: docker:stable-git
     steps:
       - checkout
+      - multirepo/run-job-for-paths
+          paths: sed 's|\([^\/]*\).*|\1|'
+      # - run:
+      #     name: Check if job should run
+          # command: |
+          #   cd << parameters.working_directory >>
+
+          #   upstream="$(git merge-base HEAD << parameters.upstream_branch >>)"
+          #   echo "Comparing to upstream commit $upstream"
+
+          #   <<# parameters.run_on_upstream >>
+          #   if [[ "$(git rev-parse HEAD)" == "$upstream" ]]; then
+          #     echo "HEAD matches upstream, running with no diff"
+          #     exit 0
+          #   fi
+          #   <</ parameters.run_on_upstream >>
+
+          #   if [[ -z "$upstream" ]]; then
+          #     echo "git merge-base failed"
+          #     exit 1
+          #   fi
+  
+          #   # Print the diff
+          #   PAGER=cat git diff --stat=80 $upstream -- << parameters.paths >>
+  
+          #   # Halt if no diff
+          #   if git diff --quiet $upstream -- << parameters.paths >>; then
+          #     echo "Skipping job, no files modified"
+          #     circleci-agent step halt
+          #   fi
       - run:
           name: Before Steps
           command: |
             # apk update && apk add curl && apk add --no-cache bash git openssh
-            export NEW_REF=$CI_COMMIT_SHA
+            echo "Resetting $target_branch to where the remote version is..."
+            git checkout -q $target_branch
+            git reset --hard -q origin/$target_branch
+            git checkout -q $CIRCLE_BRANCH
+
+            echo "Getting list of changed files..."
+            export NEW_REF=$CIRCLE_SHA1
             if [ $CI_MERGE_REQUEST_TARGET_BRANCH_NAME ]; then export BASE_REF="origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"; else export BASE_REF="$CI_COMMIT_BEFORE_SHA";  fi
             echo $BASE_REF
             echo $NEW_REF
